name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npx jest --verbose --coverage

      - name: Generate test report
        run: npm run test:report

      - name: Upload HTML test report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: html-test-report
          path: tests_report.html

      - name: Upload JUnit test report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: junit-test-report
          path: test-report.xml

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/
